### ISSUE TITLE
unittests not compiling with gcc-11.1.0

### ISSUE THREAD

**Issue by elfenpiff** [eclipse-cyclonedds/cyclonedds-cxx#162] opened 2021-09-28 15:41 UTC
When compiling cyclonedds-cxx with gcc-11.1.0 with the following commands:

```sh
cmake -Bbuild -H. -DBUILD_TESTING=ON -DCMAKE_CXX_COMPILER=/usr/bin/g++-11
cd build
make
```

the compilation fails for every unit tests with a very long compiler error like:

```
                 from /usr/include/gtest/gtest.h:64,
/home/elchris/Development/cyclonedds-cxx/src/ddscxx/tests/Bounded.cpp:47:9:   required from here
/usr/include/gtest/gtest-printers.h:291:36: error: no matching function for call to ‘testing::internal::internal_stream_operator_without_lexical_na
me_lookup::StreamPrinter::PrintValue(const dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>&, std::null
ptr_t)’
  291 |     T, decltype(Printer::PrintValue(std::declval<const T&>(), nullptr)),
      |                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/gtest/gtest-printers.h:212:15: note: candidate: ‘template<class T, class, class> static void testing::internal::internal_stream_operat
or_without_lexical_name_lookup::StreamPrinter::PrintValue(const T&, std::ostream*)’
  212 |   static void PrintValue(const T& value, ::std::ostream* os) {
      |               ^~~~~~~~~~
/usr/include/gtest/gtest-printers.h:212:15: note:   template argument deduction/substitution failed:
/usr/include/gtest/gtest-printers.h:211:33: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘const dds::domain::
TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>’)
  210 |             typename = decltype(std::declval<std::ostream&>()
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  211 |                                 << std::declval<const T&>())>
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/gtest/gtest.h:58,
                 from /home/elchris/Development/cyclonedds-cxx/src/ddscxx/tests/Bounded.cpp:12:
/usr/include/c++/11.1.0/ostream:108:7: note: candidate: ‘std::basic_ostream<_CharT, _Traits>::__ostream_type& std::basic_ostream<_CharT, _Traits>::operator<<(std::basic_ostream<_CharT, _Traits>::__ostream_type& (*)(std::basic_ostream<_CharT, _Traits>::__ostream_type&)) [with _CharT = char; _Traits = std::char_traits<char>; std::basic_ostream<_CharT, _Traits>::__ostream_type = std::basic_ostream<char>]’
  108 |       operator<<(__ostream_type& (*__pf)(__ostream_type&))
      |       ^~~~~~~~

```

It continues for several pages ...

**Comment by k0ekk0ek** [comment] 2021-12-09 13:39
Hi @elfenpiff. Sorry about the overdue reply. If you include the changes proposed in #184, you should be good. Hopefully, it won't be long before it's merged into master. Thanks for the report!

**Comment by k0ekk0ek** [comment] 2021-12-15 08:36
@eboasson, since the PR is merged I think we can close this one.

**Comment by javiersorianoruiz** [comment] 2022-09-06 10:48
Hello.

We (@Bit-Seq and me) have tried to compile `cyclonedds-cxx (version 0.10.1)` with `g++11` and `-DBUILD_TESTING=ON` and the compilation error appears (see below).

Without `-DBUILD_TESTING=ON` we can compile with no problem.

Do you know how to compile `cyclonedds-cxx`  with `g++11` building testing at the same time?

```
In file included from /usr/local/include/gtest/gtest-matchers.h:48,
                 from /usr/local/include/gtest/internal/gtest-death-test-internal.h:46,
                 from /usr/local/include/gtest/gtest-death-test.h:43,
                 from /usr/local/include/gtest/gtest.h:60,
                 from /root/cyclonedds-cxx/src/ddscxx/tests/Bounded.cpp:12:
/usr/local/include/gtest/gtest-printers.h: In instantiation of 'struct testing::internal::FindFirstPrinter<dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>, void, testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter, testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, testing::internal::FallbackPrinter>':
/usr/local/include/gtest/gtest-printers.h:286:8:   required from 'struct testing::internal::FindFirstPrinter<dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>, void, testing::internal::ContainerPrinter, testing::internal::FunctionPointerPrinter, testing::internal::PointerPrinter, testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter, testing::internal::ProtobufPrinter, testing::internal::ConvertibleToIntegerPrinter, testing::internal::ConvertibleToStringViewPrinter, testing::internal::RawBytesPrinter, testing::internal::FallbackPrinter>'
/usr/local/include/gtest/gtest-printers.h:306:9:   required from 'void testing::internal::PrintWithFallback(const T&, std::ostream*) [with T = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; std::ostream = std::basic_ostream<char>]'
/usr/local/include/gtest/gtest-printers.h:440:30:   [ skipping 2 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
/usr/local/include/gtest/gtest-printers.h:999:30:   required from 'void testing::internal::UniversalPrint(const T&, std::ostream*) [with T = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; std::ostream = std::basic_ostream<char>]'
/usr/local/include/gtest/gtest-printers.h:884:19:   required from 'static void testing::internal::UniversalTersePrinter<T>::Print(const T&, std::ostream*) [with T = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; std::ostream = std::basic_ostream<char>]'
/usr/local/include/gtest/gtest-printers.h:1037:44:   required from 'std::string testing::PrintToString(const T&) [with T = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; std::string = std::__cxx11::basic_string<char>]'
/usr/local/include/gtest/gtest-printers.h:333:36:   required from 'static std::string testing::internal::FormatForComparison<ToPrint, OtherOperand>::Format(const ToPrint&) [with ToPrint = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; OtherOperand = dds::core::null_type; std::string = std::__cxx11::basic_string<char>]'
/usr/local/include/gtest/gtest-printers.h:414:45:   required from 'std::string testing::internal::FormatForComparisonFailureMessage(const T1&, const T2&) [with T1 = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; T2 = dds::core::null_type; std::string = std::__cxx11::basic_string<char>]'
/usr/local/include/gtest/gtest.h:1412:63:   required from 'testing::AssertionResult testing::internal::CmpHelperOpFailure(const char*, const char*, const T1&, const T2&, const char*) [with T1 = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; T2 = dds::core::null_type]'
/usr/local/include/gtest/gtest.h:1436:1:   required from 'testing::AssertionResult testing::internal::CmpHelperNE(const char*, const char*, const T1&, const T2&) [with T1 = dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>; T2 = dds::core::null_type]'
/root/cyclonedds-cxx/src/ddscxx/tests/Bounded.cpp:47:9:   required from here
/usr/local/include/gtest/gtest-printers.h:290:36: error: no matching function for call to 'testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>&, std::nullptr_t)'
  290 |     T, decltype(Printer::PrintValue(std::declval<const T&>(), nullptr)),
      |                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/gtest/gtest-printers.h:213:15: note: candidate: 'template<class T, class, class> static void testing::internal::internal_stream_operator_without_lexical_name_lookup::StreamPrinter::PrintValue(const T&, std::ostream*)'
  213 |   static void PrintValue(const T& value, ::std::ostream* os) {
      |               ^~~~~~~~~~
/usr/local/include/gtest/gtest-printers.h:213:15: note:   template argument deduction/substitution failed:
/usr/local/include/gtest/gtest-printers.h:212:33: error: no match for 'operator<<' (operand types are 'std::basic_ostream<char>' and 'const dds::domain::TDomainParticipant<org::eclipse::cyclonedds::domain::DomainParticipantDelegate>')
  211 |             typename = decltype(std::declval<std::ostream&>()
      |                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  212 |                                 << std::declval<const T&>())>
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~

```

Kind regards.

**Comment by javiersorianoruiz** [comment] 2022-09-12 06:53
Finally, I have been able to reproduce the compilation problem, I have had to create a container with docker with the following environment.
- Docker version 20.10.17, build 100c701
- Ubuntu 20.04 LTS
- google test 1.12.1
- cyclonedds-cxx and cyclonedds 0.10.0
- gcc 11.1.0 (in our old environment where the problem it wasn't reproduce we were using gcc 9.4.0, the rest of tools and sw had the same version)
- cmake 3.16.3

I have written this DockerFile

```
FROM        ubuntu:20.04

# update and install dependencies
RUN         apt-get update \
                && apt-get install -y \
                    software-properties-common \
                    wget \
                && add-apt-repository -y ppa:ubuntu-toolchain-r/test \
                && apt-get update \
                && apt-get install -y \
                    make \
                    git \
                    curl \
                    vim \
                && apt-get install -y cmake \
                && apt-get install -y gcc-11 \
                && apt-get install -y g++-11 \
                && update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100 \
                && update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100

WORKDIR /root/

#cyclonedds compilation and installation
RUN git clone https://github.com/eclipse-cyclonedds/cyclonedds.git --branch 0.10.1
WORKDIR /root/cyclonedds/
RUN mkdir build
WORKDIR /root/cyclonedds/build
RUN cmake -DCMAKE_INSTALL_PREFIX=/usr/local/lib/cyclonedds -DBUILD_EXAMPLES=ON ..
RUN cmake --build .
RUN cmake --build . --target install

#googletest compilation and installation
WORKDIR /root/
RUN git clone https://github.com/google/googletest.git -b release-1.12.1
WORKDIR /root/googletest/
RUN mkdir build
WORKDIR /root/googletest/build
RUN cmake ..
RUN make
RUN make install



#cyclonedds-cxx compilation and installation
WORKDIR /root/
RUN git clone https://github.com/eclipse-cyclonedds/cyclonedds-cxx.git --branch 0.10.1
WORKDIR /root/cyclonedds-cxx/
RUN mkdir build
WORKDIR /root/cyclonedds-cxx/build
RUN cmake   -DCMAKE_INSTALL_PREFIX=/usr/local/lib/cyclonedds-cxx \
            -DCMAKE_PREFIX_PATH=/usr/local/lib/cyclonedds \
#If I compile with the test of gtest appears the compilation error issue 252
#https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/252
#            -DBUILD_TESTING=ON \
            -DBUILD_EXAMPLES=ON \
            -DCMAKE_BUILD_TYPE=Debug \
            ..
RUN cmake --build .
RUN cmake --build . --target install

#copy and compilation example to reproduce issue 252
#https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/252
WORKDIR /root/
ADD issue_252 /root/issue_252
RUN rm -rf /root/issue_252/build
RUN mkdir /root/issue_252/build
WORKDIR /root/issue_252/build/
RUN cmake ..
RUN make
```

With this environment I have also been able to reproduce the other related issue (#252)

**Comment by javiersorianoruiz** [comment] 2022-09-21 10:11
We (@Bit-Seq, @jordialexalar and me) have found a workaround to solve this problem and #252 too. 

The change consists in adding a new constructor at the template TInstanceHandle in the following way:

File: cyclonedds-cxx/src/ddscxx/include/dds/core/**TInstanceHandle.hpp**

```
     /**
     * @cond
     * Workaround issues 252 and 162
     * constructor for creating an instance-handle
     * from dds_instance_handle_t type.
     */
    TInstanceHandle(const dds_instance_handle_t& other);
```

File: cyclonedds-cxx/src/ddscxx/include/dds/core/detail/**TInstanceHandleImpl.hpp**


```
template <typename DELEGATE>
TInstanceHandle<DELEGATE>::TInstanceHandle(const dds_instance_handle_t& other) 
    : dds::core::Value<DELEGATE>(other) {
}

```

In this file **TInstanceHandleImpl.hpp** it is also needed to overload the operator `<<` in the following way:

```
//Overloaded operator << (workaround issues 252 and 162)
inline std::ostream& operator << (std::ostream& os, const dds::core::TInstanceHandle<org::eclipse::cyclonedds::core::InstanceHandleDelegate> h)
{
     os << h.delegate();
     return os;
}

```

We are going to create a fork for this repository, and we will ask for a pull request with the implemented changes.

**Comment by javiersorianoruiz** [comment] 2022-09-21 11:49
#09b5807faacdd6c8d0189a82935f8cecfaec9769

**Comment by elfenpiff** [comment] 2022-09-21 12:45
@javiersorianoruiz sounds great, looking forward to it.

**Comment by javiersorianoruiz** [comment] 2022-09-29 08:52
@eboasson, this issue, and the issue https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/252, can they be closed after merging  the PR (https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/324)?

**Comment by eboasson** [comment] 2022-09-29 10:13
> @eboasson, this issue, and the issue https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/252, can they be closed after merging the PR (https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/324)?

Yes, indeed! Thanks for reminding me 🙂

**Closed by eboasson** 2022-09-29 10:13 UTC
