### ISSUE TITLE
Issues with the updated IDL C++ generator

### ISSUE THREAD

**Issue by sumanth-nirmal** [eclipse-cyclonedds/cyclonedds-cxx#77] opened 2021-05-13 04:43 UTC
### Required Information

**Operating system:**
Ubuntu 18.04 LTS

**Compiler version:**
GCC 7.5.0

**Cyclone Version**
- cyclonedds - master branch, https://github.com/eclipse-cyclonedds/cyclonedds/commit/9e0d5bc69f83795e0b0855c2e4afdeecfd6b687c)
- cyclonedds-cxx - template_streaming , https://github.com/eclipse-cyclonedds/cyclonedds-cxx/commit/39ffc05dd419ecd661c8f4d090289b4fc6ed9f5f
**Update** Issues from 2 are using 
- cyclonedds-cxx - template_streaming , https://github.com/eclipse-cyclonedds/cyclonedds-cxx/commit/39ffc05dd419ecd661c8f4d090289b4fc6ed9f5f rebased onto https://github.com/reicheratwork/cyclonedds-cxx/tree/templated_streaming_improved

### Observed result or behavior
I have tried the updated IDL C++ generator and have encountered the following problems.

1. [x] The generated code for IDL containing an array of basic types, doesn't compile 
    The problem I think is because the generated code has something like below, where its trying to convert an array to a basic type
    ```
      idl_array<bool, 10> bool_value__ = { };
      bool bool_value_() const { return this->bool_value__; }
    ```
    The compile error is as follows:
     ```
    error: cannot convert ‘const idl_array<bool, 10>’ to ‘bool’ in return
       bool bool_value_() const { return this->bool_value__; }
                                               ^~~~~~~~~~~~
    ```
    **Updated:** Then I realized this might be fixed with this MR https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/76 and it did fix this specific issue, but still have the following issues.
2. [x] Redeclaration of loop variable when IDL has an array, the generated code for `read`, `write` looks as below (where `_a` is redeclared)
    ```
    for (uint32_t _a = 0; _a < 10; _a++) {
    write(str, instance.bool_value_()[_a]);
    } //_a
    for (uint32_t _a = 0; _a < 10; _a++) {
    write(str, instance.byte_value_()[_a]);
    } //_a
    ```
3. [x] Redeclaration of a variable when IDL has a sequence, the generated code for `read`, `write` looks as below (where `se_0` is redeclared)
    ```
    uint32_t se_0 = std::min<uint32_t>(uint32_t(instance.bool_value_().size()), 10);
    write(str, se_0);
    for (uint32_t i_0 = 0; i_0 < se_0; i_0++) {
    write(str, instance.bool_value_()[i_0]);
    } //i_0
    uint32_t se_0 = std::min<uint32_t>(uint32_t(instance.byte_value_().size()), 10);
    write(str, se_0);
    for (uint32_t i_0 = 0; i_0 < se_0; i_0++) {
    write(str, instance.byte_value_()[i_0]);
    } //i_0
    ```
4. [x]  The nested IDL is included as `<nested_idl_file_path>.h`, but should be included as `.hpp` maybe here https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/templated-streaming/src/idlcxx/src/generator.c#L638
5. [x] Ambiguous setter functions for strings (probably also true for other types) in the generated code, below shows the generated code
    ```
    void string_value_(const std::string _val_) { this->string_value__ = _val_; }
    void string_value_(std::string&& _val_) { this->string_value__ = _val_; }
    ```
    These 2 const and rvalue reference are pretty much the same, probably we should use const lvalue ref and rvalue ref for the setter functions.
6. [x] The generated code for the unbounded sequence of bools doesn't compile, below is the compilation error 
    ```
    /home/sumanth.nirmal/cyclone_ws/cyclonedds-cxx/cmake-build-debug/examples/helloworld/HelloWorldData.hpp:170:7: error: no matching function for call to ‘read(basic_cdr_stream&, std::vector<bool>::reference)’
   read(str, instance.bool_value()[i_1]);
   ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ```
7. [ ] Not everything required in [`TopicTraits.hpp`](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/899f4efc1e5983f13c67227afe450c8f0107af87/src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp) is included,
    - [x] `std::vector` is not included (though used [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/899f4efc1e5983f13c67227afe450c8f0107af87/src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp#L41))
    - [x] I am also not sure if `<string.h>` is required, if required then shouldn't this be included as `<cstring>`?
    - [ ] `ddsi_sertype` is not included (though used [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/899f4efc1e5983f13c67227afe450c8f0107af87/src/ddscxx/include/org/eclipse/cyclonedds/topic/TopicTraits.hpp#L66). I am not sure if the assumption here is that these will be included with `#include "dds/dds.hpp"` from the application.
8. [x] Include directory option `-I <directory>` with the IDL compiler is not considered. \
    Consider the following nested IDL [nested_idl_setup.zip](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/files/6519888/nested_idl_setup.zip) (where the included IDL is in a different path), and invoke the IDL compiler as below:
    ```
    // unzip the nested_idl_setup folder and run the following command from this folder
   ~/cyclone_ws/cyclonedds/build/bin/idlc -I /home/sumanth.nirmal/tooch/new_idl/nested_idl_setup/foo/bar/other/builtin_interfaces/ -l ~/cyclone_ws/cyclonedds-cxx/build/lib/libidlcxx.so -f case-sensitive Clock.idl 
    ```
    This gives the following error
    ```
    /home/sumanth.nirmal/tooch/new_idl/nested_idl_setup/Clock.idl:1: error: Can't open include file "builtin_interfaces/msg/Time.idl"
    #include "builtin_interfaces/msg/Time.idl"
    1 error in preprocessor.
    ```

**Comment by k0ekk0ek** [comment] 2021-05-19 13:45
Last point is different in the spec as well. Other issues have been fixed in the meantime.

**Comment by sumanth-nirmal** [comment] 2021-05-20 15:14
@k0ekk0ek Thanks, I can confirm all the points except the last point are resolved with the latest `templated_streaming` branch (https://github.com/eclipse-cyclonedds/cyclonedds-cxx/commit/899f4efc1e5983f13c67227afe450c8f0107af87)

**Comment by sumanth-nirmal** [comment] 2021-05-21 00:45
@k0ekk0ek @reicheratwork I ran into some more issues with the IDL C++ generator and updated this same issue with the findings.

**Comment by reicheratwork** [comment] 2021-05-21 08:35
@sumanth-nirmal let me see what is going wrong

**Comment by reicheratwork** [comment] 2021-06-07 12:10
> 5\. Ambiguous setter functions for strings (probably also true for other types) in the generated code, below shows the generated code

This seems to be an error, the const setter should be taking a reference, not a value.

Will fix.

**Comment by reicheratwork** [comment] 2021-06-07 12:10
> 6\. The generated code for the unbounded sequence of bools doesn't compile, below is the compilation error

This is now fixed.

**Comment by k0ekk0ek** [comment] 2021-06-09 12:29
@sumanth-nirmal, like we discussed offline, the `-I` option works as expected. The only thing that we/I thought could be an error is when you set `-I` to a subdirectory, e.g. `foo` if there's a subdirectory `foo/bar`, the entire relative path is resolved. I've playing around with it a little, but I'm actually not sure what the expected behavior should be. Currently it includes the normalized relative path and I think that's actually the sanest behavior. e.g. say you're in `foo/bar/foobar.idl` include `baz/foobaz.idl` from `foo/baz/foobaz.idl` by passing `-Ifoo`. Currently that becomes `../baz/foobaz.h`. I don't know what else that should be. On the one hand you could state that the original directive converted to include `.hpp` instead of `.idl` is the right behavior, on the other just using the relative path kind of makes sense. Any thoughts?

**Comment by sumanth-nirmal** [comment] 2021-06-09 19:49
@k0ekk0ek Agree that `-I` option seems to work as expected, sorry it was my bad that I messed up the path when invoking the IDL compiler.

Using the normalized relative path for the included IDL in the generated code is reasonable but not that useful because, if we want to use these generated files in some other project then we need to replicate the path which the generated files expect. Also using the absolute path for the included IDL in the generated code is not the best because of similar reasons. \
Thinking about this I think the best is to just use the original include directive of the `.idl` and just change the extension to `.hpp` e.g. if `foo/bar/foobar.idl` include `baz/foobaz.idl` from `foo/baz/foobaz.idl` by passing `-I foo`, then the generated code includes this as `#include "baz/foobaz.hpp"`
This approach has a definitive behavior always that it uses the original include directive of the IDL, and if we want to use this with other projects then we can use the include directories to point to the generated code. I think this is the best approach rather than to deal with relative and nested paths. Does it make sense?

**Comment by k0ekk0ek** [comment] 2021-06-10 08:35
@sumanth-nirmal, I actually thought the same thing but that's a bit more work because the preprocessor doesn't output them (which is exactly what the preprocessor should do for C/C++), so I have to solve that problem a bit differently. I've created [#832](https://github.com/eclipse-cyclonedds/cyclonedds/issues/832) to track progress.

**Comment by sumanth-nirmal** [comment] 2021-06-10 16:03
@k0ekk0ek Thanks, let us worry about this in #832 and we can probably check this point off in this issue.

**Closed** 2021-06-11 09:17 UTC
